; IDs referenced by the restored Bank 00 text sound-command table.

DEF SFX_GET_ITEM_1 EQU $86
DEF SFX_GET_ITEM_2 EQU $89
DEF SFX_POKEDEX_RATING EQU $91
DEF SFX_GET_KEY_ITEM EQU $94
DEF SFX_DEX_PAGE_ADDED EQU $98
DEF SFX_CAUGHT_MON EQU $9A

; Generation I internal species IDs used by text cry commands.
DEF NIDORINA_INTERNAL_ID EQU $A8
DEF PIDGEOT_INTERNAL_ID EQU $97
DEF DEWGONG_INTERNAL_ID EQU $78
