; IDs referenced by the restored Bank 00 audio/text code.

DEF SFX_GET_ITEM_1 EQU $86
DEF SFX_GET_ITEM_2 EQU $89
DEF SFX_POKEDEX_RATING EQU $91
DEF SFX_GET_KEY_ITEM EQU $94
DEF SFX_DEX_PAGE_ADDED EQU $98
DEF SFX_CAUGHT_MON EQU $9A
DEF SFX_STOP_ALL_MUSIC EQU $FF

DEF MUSIC_BIKE_RIDING EQU $D2
DEF MUSIC_SURFING EQU $D6
DEF AUDIO_BANK_BIKE_SURF EQU $1F

DEF AUDIO_BANK_1 EQU $02
DEF AUDIO_BANK_2 EQU $08

DEF CHAN5 EQU 4
DEF CHAN6 EQU 5
DEF CHAN7 EQU 6
DEF CHAN8 EQU 7

DEF BIT_BATTLE_OVER_OR_BLACKOUT EQU 5
DEF BIT_NO_AUDIO_FADE_OUT EQU 1

; Generation I internal species IDs used by text cry commands.
DEF NIDORINA_INTERNAL_ID EQU $A8
DEF PIDGEOT_INTERNAL_ID EQU $97
DEF DEWGONG_INTERNAL_ID EQU $78
