; Verified ROM0 targets from the uploaded Pocket Monsters Midori ROMs.
; These are temporary address constants until each target is restored as a label.

DEF BANK00_VBLANK_ADDR EQU $0AAC
DEF BANK00_SERIAL_ADDR EQU $0BA7
DEF BANK00_INIT_ADDR EQU $09DA
DEF BANK00_DELAY_FRAME_ADDR EQU $0B31
DEF BANK00_GET_ROWCOL_BG_ADDR EQU $0774

; Forward targets inside the text engine. These remain fixed across both revisions
; and are replaced by labels as their routines are restored.
DEF BANK00_NULL_CHAR_ADDR EQU $04C9
DEF BANK00_PRINT_PLAYER_NAME_ADDR EQU $04DA
DEF BANK00_PRINT_RIVAL_NAME_ADDR EQU $04E0
DEF BANK00_TRAINER_CHAR_ADDR EQU $04E6
DEF BANK00_TM_CHAR_ADDR EQU $04EC
DEF BANK00_PC_CHAR_ADDR EQU $04F2
DEF BANK00_ROCKET_CHAR_ADDR EQU $04F8
DEF BANK00_PLACE_POKE_ADDR EQU $04FE
DEF BANK00_SIX_DOTS_CHAR_ADDR EQU $0504
DEF BANK00_PLACE_MOVE_TARGET_ADDR EQU $050A
DEF BANK00_PLACE_MOVE_USER_ADDR EQU $0510
DEF BANK00_CONT_TEXT_ADDR EQU $0555
DEF BANK00_PROMPT_TEXT_ADDR EQU $0569
DEF BANK00_DONE_TEXT_ADDR EQU $0581
DEF BANK00_PARAGRAPH_ADDR EQU $0588
DEF BANK00_CONT_TEXT_INTERNAL_ADDR EQU $05A9
DEF BANK00_CONT_TEXT_NO_PAUSE_ADDR EQU $05BB
DEF BANK00_TEXT_COMMAND_PROCESSOR_ADDR EQU $05F1

IF DEF(_REV0)
    DEF BANK00_TIMER_ADDR EQU $0D9A
    DEF BANK00_DELAY_FRAMES_ADDR EQU $3781
    DEF BANK00_JOYPAD_LOW_SENSITIVITY_ADDR EQU $3879
    DEF BANK00_MANUAL_TEXT_SCROLL_ADDR EQU $38E1
    DEF BANK00_PRINT_LETTER_DELAY_ADDR EQU $391D
    DEF BANK00_DELAY3_ADDR EQU $3E07
ELIF DEF(_REVA)
    DEF BANK00_TIMER_ADDR EQU $0D88
    DEF BANK00_DELAY_FRAMES_ADDR EQU $376F
    DEF BANK00_JOYPAD_LOW_SENSITIVITY_ADDR EQU $3867
    DEF BANK00_MANUAL_TEXT_SCROLL_ADDR EQU $38CF
    DEF BANK00_PRINT_LETTER_DELAY_ADDR EQU $390B
    DEF BANK00_DELAY3_ADDR EQU $3DF5
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
