; Verified ROM0 targets from the uploaded Pocket Monsters Midori ROMs.
; These are temporary address constants until each target is restored as a label.

DEF BANK00_VBLANK_ADDR EQU $0AAC
DEF BANK00_SERIAL_ADDR EQU $0BA7
DEF BANK00_INIT_ADDR EQU $09DA
DEF BANK00_DELAY_FRAME_ADDR EQU $0B31
DEF BANK00_GET_ROWCOL_BG_ADDR EQU $0774
DEF BANK00_WRITE_DMA_CODE_ADDR EQU $4750
DEF BANK00_PREPARE_OAM_DATA_ADDR EQU $4672
DEF BANK00_PREPARE_TITLE_SCREEN_ADDR EQU $476E
DEF BANK00_AUDIO1_UPDATE_ADDR EQU $4000
DEF BANK00_AUDIO1_PLAY_SOUND_ADDR EQU $4773
DEF BANK00_MUSIC_LOW_HEALTH_ADDR EQU $6C38
DEF BANK00_AUDIO2_UPDATE_ADDR EQU $455F
DEF BANK00_AUDIO2_PLAY_SOUND_ADDR EQU $4D1B
DEF BANK00_AUDIO3_UPDATE_ADDR EQU $4417
DEF BANK00_AUDIO3_PLAY_SOUND_ADDR EQU $4B8A
DEF BANK00_TRACK_PLAY_TIME_ADDR EQU $4DEE
DEF BANK00_PRINT_WAITING_TEXT_ADDR EQU $49EE

; Fixed ROMX targets referenced by the restored text-script hub.
DEF BANK04_UPDATE_SPRITE_FACING_ADDR EQU $5AD7
DEF BANK05_INIT_MAP_SPRITES_ADDR EQU $7840
DEF BANK07_PRINT_SAFARI_GAME_OVER_TEXT_ADDR EQU $7A99
DEF BANK1D_VENDING_MACHINE_MENU_ADDR EQU $4E36

; Forward targets inside the text engine. These remain fixed across both revisions
; and are replaced by labels as their routines are restored.
DEF BANK00_NULL_CHAR_ADDR EQU $04C9
DEF BANK00_PRINT_PLAYER_NAME_ADDR EQU $04DA
DEF BANK00_PRINT_RIVAL_NAME_ADDR EQU $04E0
DEF BANK00_TRAINER_CHAR_ADDR EQU $04E6
DEF BANK00_TM_CHAR_ADDR EQU $04EC
DEF BANK00_PC_CHAR_ADDR EQU $04F2
DEF BANK00_ROCKET_CHAR_ADDR EQU $04F8
DEF BANK00_PLACE_POKE_ADDR EQU $04FE
DEF BANK00_SIX_DOTS_CHAR_ADDR EQU $0504
DEF BANK00_PLACE_MOVE_TARGET_ADDR EQU $050A
DEF BANK00_PLACE_MOVE_USER_ADDR EQU $0510
DEF BANK00_CONT_TEXT_ADDR EQU $0555
DEF BANK00_PROMPT_TEXT_ADDR EQU $0569
DEF BANK00_DONE_TEXT_ADDR EQU $0581
DEF BANK00_PARAGRAPH_ADDR EQU $0588
DEF BANK00_CONT_TEXT_INTERNAL_ADDR EQU $05A9
DEF BANK00_CONT_TEXT_NO_PAUSE_ADDR EQU $05BB
DEF BANK00_TEXT_COMMAND_PROCESSOR_ADDR EQU $05F1

IF DEF(_REV0)
    DEF BANK00_TIMER_ADDR EQU $0D9A
    DEF BANK00_PLAY_SOUND_ADDR EQU $0E45
    DEF BANK00_PLAY_CRY_ADDR EQU $2DC7
    DEF BANK00_PRINT_BCD_NUMBER_ADDR EQU $2FC4
    DEF BANK00_FARCALL_ADDR EQU $3620
    DEF BANK00_TRACK_PLAY_TIME_FARCALL_ADDR EQU BANK00_FARCALL_ADDR
    DEF BANK00_SAVE_SCREEN_TILES_ADDR EQU $3761
    DEF BANK00_LOAD_SCREEN_TILES_ADDR EQU $376D
    DEF BANK00_FILL_MEMORY_ADDR EQU $372A
    DEF BANK00_DELAY_FRAMES_ADDR EQU $3781
    DEF BANK00_WAIT_FOR_SOUND_ADDR EQU $3790
    DEF BANK00_JOYPAD_LOW_SENSITIVITY_ADDR EQU $3879
    DEF BANK00_WAIT_FOR_TEXT_SCROLL_ADDR EQU $38AE
    DEF BANK00_MANUAL_TEXT_SCROLL_ADDR EQU $38E1
    DEF BANK00_PRINT_LETTER_DELAY_ADDR EQU $391D
    DEF BANK00_PRINT_TEXT_ADDR EQU $3C79
    DEF BANK00_PRINT_TEXT_NO_BOX_ADDR EQU $3C89
    DEF BANK00_PRINT_NUMBER_ADDR EQU $3C8F
    DEF BANK00_GB_PAL_NORMAL_ADDR EQU $3E0C
    DEF BANK00_GB_PAL_WHITE_OUT_ADDR EQU $3E15
    DEF BANK00_RANDOM_ADDR EQU $3E8C
    DEF BANK00_PREDEF_ADDR EQU $3E9D
    DEF BANK00_DELAY3_ADDR EQU $3E07
    DEF BANK00_FADE_OUT_AUDIO_ADDR EQU $139C
    DEF BANK00_SWITCH_TO_MAP_ROM_BANK_ADDR EQU $2CCD
    DEF BANK00_LOAD_PLAYER_SPRITE_GFX_ADDR EQU $23AE
    DEF BANK00_LOAD_CURRENT_MAP_VIEW_ADDR EQU $26BB
    DEF BANK00_TEXTSCRIPT_ITEM_STORAGE_PC_ADDR EQU $34AA
    DEF BANK00_TEXTSCRIPT_BILLS_PC_ADDR EQU $34B4
    DEF BANK00_TEXTSCRIPT_PRIZE_VENDOR_ADDR EQU $34BE
    DEF BANK00_TEXTSCRIPT_POKECENTER_PC_ADDR EQU $34C9
    DEF BANK00_DISPLAY_START_MENU_ADDR EQU $15DE
    DEF BANK01_DISPLAY_TEXT_ID_INIT_ADDR EQU $724C
    DEF BANK01_CABLE_CLUB_NPC_ADDR EQU $736C
    DEF BANK01_POKEMART_DIALOGUE_ADDR EQU $6BBC
    DEF BANK01_POKECENTER_DIALOGUE_ADDR EQU $7122
ELIF DEF(_REVA)
    DEF BANK00_TIMER_ADDR EQU $0D88
    DEF BANK00_PLAY_SOUND_ADDR EQU $0E33
    DEF BANK00_PLAY_CRY_ADDR EQU $2DB5
    DEF BANK00_PRINT_BCD_NUMBER_ADDR EQU $2FB2
    DEF BANK00_FARCALL_ADDR EQU $360E
    DEF BANK00_TRACK_PLAY_TIME_FARCALL_ADDR EQU BANK00_FARCALL_ADDR
    DEF BANK00_SAVE_SCREEN_TILES_ADDR EQU $374F
    DEF BANK00_LOAD_SCREEN_TILES_ADDR EQU $375B
    DEF BANK00_FILL_MEMORY_ADDR EQU $3718
    DEF BANK00_DELAY_FRAMES_ADDR EQU $376F
    DEF BANK00_WAIT_FOR_SOUND_ADDR EQU $377E
    DEF BANK00_JOYPAD_LOW_SENSITIVITY_ADDR EQU $3867
    DEF BANK00_WAIT_FOR_TEXT_SCROLL_ADDR EQU $389C
    DEF BANK00_MANUAL_TEXT_SCROLL_ADDR EQU $38CF
    DEF BANK00_PRINT_LETTER_DELAY_ADDR EQU $390B
    DEF BANK00_PRINT_TEXT_ADDR EQU $3C67
    DEF BANK00_PRINT_TEXT_NO_BOX_ADDR EQU $3C77
    DEF BANK00_PRINT_NUMBER_ADDR EQU $3C7D
    DEF BANK00_GB_PAL_NORMAL_ADDR EQU $3DFA
    DEF BANK00_GB_PAL_WHITE_OUT_ADDR EQU $3E03
    DEF BANK00_RANDOM_ADDR EQU $3E7A
    DEF BANK00_PREDEF_ADDR EQU $3E8B
    DEF BANK00_DELAY3_ADDR EQU $3DF5
    DEF BANK00_FADE_OUT_AUDIO_ADDR EQU $138A
    DEF BANK00_SWITCH_TO_MAP_ROM_BANK_ADDR EQU $2CBB
    DEF BANK00_LOAD_PLAYER_SPRITE_GFX_ADDR EQU $239C
    DEF BANK00_LOAD_CURRENT_MAP_VIEW_ADDR EQU $26A9
    DEF BANK00_TEXTSCRIPT_ITEM_STORAGE_PC_ADDR EQU $3498
    DEF BANK00_TEXTSCRIPT_BILLS_PC_ADDR EQU $34A2
    DEF BANK00_TEXTSCRIPT_PRIZE_VENDOR_ADDR EQU $34AC
    DEF BANK00_TEXTSCRIPT_POKECENTER_PC_ADDR EQU $34B7
    DEF BANK00_DISPLAY_START_MENU_ADDR EQU $15CC
    DEF BANK01_DISPLAY_TEXT_ID_INIT_ADDR EQU $71F1
    DEF BANK01_CABLE_CLUB_NPC_ADDR EQU $7311
    DEF BANK01_POKEMART_DIALOGUE_ADDR EQU $6B61
    DEF BANK01_POKECENTER_DIALOGUE_ADDR EQU $70C7
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
