; Display/layout constants used by restored Bank 00 routines.

DEF SCREEN_WIDTH EQU 20
DEF SCREEN_HEIGHT EQU 18
DEF SCREEN_AREA EQU SCREEN_WIDTH * SCREEN_HEIGHT
DEF TILEMAP_WIDTH EQU 32
DEF TILEMAP_AREA EQU $400
DEF TILE_SIZE EQU 16

DEF vTileset EQU $9000
DEF vBGMap0 EQU $9800

DEF TRANSFER_TOP EQU 0
DEF TRANSFER_MIDDLE EQU 1
DEF TRANSFER_BOTTOM EQU 2

DEF JAPANESE_BLANK_TILE EQU $7F
