; Game Boy hardware addresses/bits used by the restored Bank 00 routines.

DEF rROMB EQU $2000
DEF rIF   EQU $FF0F
DEF rLCDC EQU $FF40
DEF rLY   EQU $FF44
DEF rIE   EQU $FFFF

DEF IE_VBLANK_BIT EQU 0
DEF LCDC_ENABLE_BIT EQU 7
DEF LCDC_ENABLE_MASK EQU 1 << LCDC_ENABLE_BIT
DEF LY_FIRST_POST_VBLANK_SCANLINE EQU 145
