; Game Boy hardware addresses/bits used by the restored Bank 00 routines.

DEF rROMB EQU $2000

DEF rSB   EQU $FF01
DEF rSC   EQU $FF02
DEF rDIV  EQU $FF04
DEF rTMA  EQU $FF06
DEF rTAC  EQU $FF07
DEF rIF   EQU $FF0F

DEF rLCDC EQU $FF40
DEF rSTAT EQU $FF41
DEF rSCY  EQU $FF42
DEF rSCX  EQU $FF43
DEF rLY   EQU $FF44
DEF rBGP  EQU $FF47
DEF rOBP0 EQU $FF48
DEF rOBP1 EQU $FF49
DEF rWY   EQU $FF4A
DEF rWX   EQU $FF4B

DEF rIE   EQU $FFFF

DEF IE_VBLANK_BIT EQU 0
DEF IE_TIMER_BIT EQU 2
DEF IE_SERIAL_BIT EQU 3
DEF IE_VBLANK EQU 1 << IE_VBLANK_BIT
DEF IE_TIMER EQU 1 << IE_TIMER_BIT
DEF IE_SERIAL EQU 1 << IE_SERIAL_BIT

DEF SC_START EQU $80
DEF SC_EXTERNAL EQU $00
DEF SC_INTERNAL EQU $01

DEF LCDC_ENABLE_BIT EQU 7
DEF LCDC_ENABLE_MASK EQU 1 << LCDC_ENABLE_BIT
DEF LCDC_ON EQU $80
DEF LCDC_DEFAULT EQU $E3
DEF LY_FIRST_POST_VBLANK_SCANLINE EQU 145
