; Joypad bit masks used by restored Bank 00 routines.

DEF PAD_A EQU $01
DEF PAD_B EQU $02
DEF PAD_SELECT EQU $04
DEF PAD_START EQU $08
DEF PAD_RIGHT EQU $10
DEF PAD_LEFT EQU $20
DEF PAD_UP EQU $40
DEF PAD_DOWN EQU $80

DEF PAD_BUTTONS EQU PAD_A | PAD_B | PAD_SELECT | PAD_START
DEF PAD_CTRL_PAD EQU PAD_RIGHT | PAD_LEFT | PAD_UP | PAD_DOWN

DEF TITLE_INTERRUPT_COMBO EQU PAD_UP | PAD_SELECT | PAD_B
DEF TITLE_ACCEPT_MASK EQU PAD_START | PAD_A
