; Inventory/money constants and verified targets used by restored Bank 00 routines.

DEF MONEY_BOX EQU $13
DEF SFX_PURCHASE EQU $B2
DEF PREDEF_ADD_BCD EQU $0B

DEF BANK03_ADD_ITEM_TO_INVENTORY_ADDR EQU $45E2
DEF BANK03_REMOVE_ITEM_FROM_INVENTORY_ADDR EQU $4652

IF DEF(_REV0)
    DEF BANK01_SUBTRACT_AMOUNT_PAID_ADDR EQU $6ABD
    DEF BANK00_DISPLAY_TEXT_BOX_ID_ADDR EQU $3130
    DEF BANK00_PLAY_SOUND_WAIT_CURRENT_ADDR EQU $3788
ELIF DEF(_REVA)
    DEF BANK01_SUBTRACT_AMOUNT_PAID_ADDR EQU $6A62
    DEF BANK00_DISPLAY_TEXT_BOX_ID_ADDR EQU $311E
    DEF BANK00_PLAY_SOUND_WAIT_CURRENT_ADDR EQU $3776
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
