; Bank 00 item wrapper targets verified from the Midori ROMs.

DEF ITEM_ENGINE_BANK EQU $03
DEF BANK03_USE_ITEM_ADDR EQU $563D
DEF BANK03_TOSS_ITEM_ADDR EQU $69C4
DEF BANK03_IS_KEY_ITEM_ADDR EQU $6A6F
