; List-menu RAM symbols and verified targets used by restored Bank 00 code.

DEF wBattleType EQU $D037
DEF wListPointer EQU $CF72
DEF wListCount EQU $D0EF
DEF wMenuItemToSwap EQU $CC35
DEF wMenuWatchMovingOutOfBounds EQU $CC37
DEF wMaxMenuItem EQU $CC28
DEF wTopMenuItemY EQU $CC24
DEF wTopMenuItemX EQU $CC25
DEF wMenuWatchedKeys EQU $CC29
DEF wMenuCursorLocation EQU $CC30
DEF wListScrollOffset EQU $CC36
DEF wCurListMenuItem EQU $CF78
DEF wCurItem EQU $CF78
DEF wWhichPokemon EQU $CF79
DEF wMaxItemQuantity EQU $CF7E
DEF wNameListIndex EQU $D092
DEF wPredefBank EQU $D094
DEF wChosenMenuItem EQU $D0F2
DEF wMenuExitMethod EQU $D0F3
DEF wPartyCount EQU $D123
DEF wPartyMonNicks EQU $D257
DEF wBoxMonNicks EQU $DE64
DEF wStatusFlags5 EQU $D6AF
DEF hJoy7 EQU $FFB7

DEF BIT_NO_TEXT_DELAY EQU 6
DEF LIST_MENU_BOX EQU $0D
DEF BANK_DISPLAY_BATTLE_MENU EQU $0F
DEF ITEMLISTMENU EQU $03
DEF CHOSE_MENU_ITEM EQU $01
DEF ITEM_NAMES_BANK EQU $01

IF DEF(_REV0)
    DEF BANK00_BANKSWITCH_HOME_ADDR EQU $3606
    DEF BANK00_BANKSWITCH_BACK_ADDR EQU $3617
    DEF BANK00_GET_NAME_ADDR EQU $37B3
    DEF BANK00_GET_ITEM_PRICE_ADDR EQU $3827
    DEF BANK00_COPY_TO_STRING_BUFFER_ADDR EQU $386E
    DEF BANK00_GET_PARTY_MON_NAME_ADDR EQU $2FB1
    DEF BANK00_PLACE_MENU_CURSOR_ADDR EQU $3BC6
    DEF BANK00_PRINT_LIST_MENU_ENTRIES_ADDR EQU $1968
    DEF BANK00_EXIT_LIST_MENU_ADDR EQU $194C
    DEF BANK01_HANDLE_ITEM_LIST_SWAPPING_ADDR EQU $6AE0
ELIF DEF(_REVA)
    DEF BANK00_BANKSWITCH_HOME_ADDR EQU $35F4
    DEF BANK00_BANKSWITCH_BACK_ADDR EQU $3605
    DEF BANK00_GET_NAME_ADDR EQU $37A1
    DEF BANK00_GET_ITEM_PRICE_ADDR EQU $3815
    DEF BANK00_COPY_TO_STRING_BUFFER_ADDR EQU $385C
    DEF BANK00_GET_PARTY_MON_NAME_ADDR EQU $2F9F
    DEF BANK00_PLACE_MENU_CURSOR_ADDR EQU $3BB4
    DEF BANK00_PRINT_LIST_MENU_ENTRIES_ADDR EQU $1956
    DEF BANK00_EXIT_LIST_MENU_ADDR EQU $193A
    DEF BANK01_HANDLE_ITEM_LIST_SWAPPING_ADDR EQU $6A85
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
