; Map/tile reload constants used by restored Bank 00 helpers.

DEF BIT_NO_BATTLES EQU 4
DEF BANK_TOWN_MAP_FLY EQU $1C
DEF TOWN_MAP_FLY_ADDR EQU $54FE

IF DEF(_REV0)
    DEF BANK00_LOAD_TILESET_TILE_PATTERN_DATA_ADDR EQU $23FF
ELIF DEF(_REVA)
    DEF BANK00_LOAD_TILESET_TILE_PATTERN_DATA_ADDR EQU $23ED
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
