; Current map-view render buffer constants verified from Bank 00.

DEF wSurroundingTiles EQU $C508
DEF wYBlockCoord EQU $D2E2
DEF wXBlockCoord EQU $D2E3

DEF SCREEN_BLOCK_HEIGHT EQU 5
DEF SCREEN_BLOCK_WIDTH EQU 6
DEF SURROUNDING_WIDTH EQU 24
DEF BLOCK_HEIGHT EQU 4

IF DEF(_REV0)
    DEF BANK00_DRAW_TILE_BLOCK_ADDR EQU $292E
ELIF DEF(_REVA)
    DEF BANK00_DRAW_TILE_BLOCK_ADDR EQU $291C
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
