; Map-script runner symbols verified from the uploaded Midori ROMs.

DEF wMapScriptPtr EQU $D2ED

DEF BANK03_TRY_PUSHING_BOULDER_ADDR EQU $7557
DEF BANK03_DO_BOULDER_DUST_ANIMATION_ADDR EQU $75E7

IF DEF(_REV0)
    DEF BANK00_RUN_NPC_MOVEMENT_SCRIPT_ADDR EQU $3156
ELIF DEF(_REVA)
    DEF BANK00_RUN_NPC_MOVEMENT_SCRIPT_ADDR EQU $3144
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
