; Name-table constants used by restored Bank 00 name helpers.

DEF wNameListType EQU $D093

DEF NAME_LENGTH EQU 6
DEF MONSTER_NAMES_BANK EQU $0E
DEF MONSTER_NAMES_ADDR EQU $5068
DEF ITEM_NAME EQU $04
DEF MOVE_NAME EQU $02
DEF MOVE_NAMES_BANK EQU $04

DEF HM01 EQU $C4
DEF TM01 EQU $C9
DEF NUM_HMS EQU 5

DEF MOVE_CUT EQU $0F
DEF MOVE_FLY EQU $13
DEF MOVE_SURF EQU $39
DEF MOVE_STRENGTH EQU $46
DEF MOVE_FLASH EQU $94

IF DEF(_REV0)
    DEF BANK00_IS_IN_ARRAY_ADDR EQU $3DDB
ELIF DEF(_REVA)
    DEF BANK00_IS_IN_ARRAY_ADDR EQU $3DC9
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
