; Overworld constants verified from the uploaded Midori ROMs.
; BIT_FLY_WARP and BIT_BATTLE_OVER_OR_BLACKOUT are already shared by
; earlier restored systems, so they are reused rather than redefined here.

DEF BIT_WILD_ENCOUNTER_COOLDOWN EQU 0
DEF BIT_DUNGEON_WARP EQU 4
DEF BIT_NO_NPC_FACE_PLAYER EQU 5
DEF BIT_CUR_MAP_LOADED_1 EQU 5
DEF BIT_CUR_MAP_LOADED_2 EQU 6
DEF BIT_LEDGE_OR_FISHING EQU 6
DEF BIT_WARP_FROM_CUR_SCRIPT EQU 3
DEF BIT_SCRIPTED_MOVEMENT_STATE EQU 7

; Fixed ROMX targets used by the Bank 00 overworld path.
DEF BANK1C_HANDLE_MID_JUMP_ADDR EQU $4DEA
DEF BANK03_CLEAR_VARIABLES_ON_ENTER_MAP_ADDR EQU $497B
DEF BANK1C_ENTER_MAP_ANIM_ADDR EQU $4A61
DEF BANK03_CHECK_FORCE_BIKE_OR_SURF_ADDR EQU $49D1
DEF BANK07_SAFARI_ZONE_CHECK_ADDR EQU $7A34

IF DEF(_REV0)
    DEF BANK00_LOAD_MAP_DATA_ADDR EQU $2C52
    DEF BANK00_RESET_STRENGTH_BIT_ADDR EQU $2CF8
    DEF BANK00_MAP_ENTRY_AFTER_BATTLE_ADDR EQU $2336
    DEF BANK00_JOYPAD_OVERWORLD_ADDR EQU $295E
    DEF BANK00_OVERWORLD_MOVE_AHEAD_ADDR EQU $1FCC
    DEF BANK00_WARP_FOUND_2_ADDR EQU $2153
    DEF BANK00_HANDLE_FLY_OR_DUNGEON_WARP_ADDR EQU $237C
    DEF BANK00_OVERWORLD_NEW_BATTLE_ADDR EQU $2043
    DEF BANK00_OVERWORLD_DISPLAY_DIALOGUE_ADDR EQU $1E9A
ELIF DEF(_REVA)
    DEF BANK00_LOAD_MAP_DATA_ADDR EQU $2C40
    DEF BANK00_RESET_STRENGTH_BIT_ADDR EQU $2CE6
    DEF BANK00_MAP_ENTRY_AFTER_BATTLE_ADDR EQU $2324
    DEF BANK00_JOYPAD_OVERWORLD_ADDR EQU $294C
    DEF BANK00_OVERWORLD_MOVE_AHEAD_ADDR EQU $1FBA
    DEF BANK00_WARP_FOUND_2_ADDR EQU $2141
    DEF BANK00_HANDLE_FLY_OR_DUNGEON_WARP_ADDR EQU $236A
    DEF BANK00_OVERWORLD_NEW_BATTLE_ADDR EQU $2031
    DEF BANK00_OVERWORLD_DISPLAY_DIALOGUE_ADDR EQU $1E88
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
