; Overworld constants verified from the uploaded Midori ROMs.
; BIT_FLY_WARP, BIT_BATTLE_OVER_OR_BLACKOUT and BIT_NO_BATTLES are already
; shared by earlier restored systems, so they are reused rather than redefined.

DEF BIT_WILD_ENCOUNTER_COOLDOWN EQU 0
DEF BIT_DUNGEON_WARP EQU 4
DEF BIT_NO_NPC_FACE_PLAYER EQU 5
DEF BIT_CUR_MAP_LOADED_1 EQU 5
DEF BIT_CUR_MAP_LOADED_2 EQU 6
DEF BIT_LEDGE_OR_FISHING EQU 6
DEF BIT_WARP_FROM_CUR_SCRIPT EQU 3
DEF BIT_SCRIPTED_MOVEMENT_STATE EQU 7
DEF BIT_UNKNOWN_5_2 EQU 2
DEF BIT_TURNING EQU 2
DEF BIT_SEEN_BY_TRAINER EQU 0
DEF BIT_NO_PREVIOUS_MAP EQU 7
DEF BIT_STANDING_ON_WARP EQU 2
DEF BIT_SPINNING EQU 7
DEF BIT_EVENT_IN_SAFARI_ZONE EQU 7
DEF BIT_TALKED_TO_TRAINER EQU 6
DEF BIT_TRAINER_BATTLE EQU 3
DEF BIT_ON_DUNGEON_WARP EQU 4
DEF BIT_EVENT_2A7 EQU 7

DEF PLAYER_DIR_RIGHT EQU $01
DEF PLAYER_DIR_LEFT EQU $02
DEF PLAYER_DIR_DOWN EQU $04
DEF PLAYER_DIR_UP EQU $08

DEF CINNABAR_GYM EQU $A6
DEF OAKS_LAB EQU $28
DEF ROUTE_17 EQU $1C

DEF wSpritePlayerStateData1YStepVector EQU $C103
DEF wSpritePlayerStateData1XStepVector EQU $C105
DEF wPlayerDirection EQU $D4A9
DEF wStepCounter EQU $D100
DEF wEventFlagsSafariZoneByte EQU $D70F
DEF wEventFlagsEvent2A7Byte EQU $D71A
DEF wIsInBattle EQU $D034
DEF wOutOfBattleBlackout EQU $D0F2
DEF wStatusFlags7 EQU $D6B2
DEF wNPCMovementScriptPointerTableNum EQU $CC57

DEF PREDEF_GET_TILE_AND_COORDS_IN_FRONT EQU $35
DEF PREDEF_TRY_LOAD_SAVE_FILE EQU $52
DEF PREDEF_APPLY_OUT_OF_BATTLE_POISON_DAMAGE EQU $13

; Fixed ROMX targets used by the Bank 00 overworld path.
DEF BANK1C_HANDLE_MID_JUMP_ADDR EQU $4DEA
DEF BANK03_CLEAR_VARIABLES_ON_ENTER_MAP_ADDR EQU $497B
DEF BANK1C_ENTER_MAP_ANIM_ADDR EQU $4A61
DEF BANK03_CHECK_FORCE_BIKE_OR_SURF_ADDR EQU $49D1
DEF BANK07_SAFARI_ZONE_CHECK_ADDR EQU $7A34
DEF BANK07_SAFARI_ZONE_CHECK_STEPS_ADDR EQU $7A43
DEF BANK11_LOAD_SPINNER_ARROW_TILES_ADDR EQU $57B0
DEF BANK00_PREPARE_FOR_SPECIAL_WARP_ADDR EQU $6261

IF DEF(_REV0)
    DEF BANK00_LOAD_MAP_DATA_ADDR EQU $2C52
    DEF BANK00_RESET_STRENGTH_BIT_ADDR EQU $2CF8
    DEF BANK00_MAP_ENTRY_AFTER_BATTLE_ADDR EQU $2336
    DEF BANK00_JOYPAD_OVERWORLD_ADDR EQU $295E
    DEF BANK00_OVERWORLD_MOVE_AHEAD_ADDR EQU $1FCC
    DEF BANK00_WARP_FOUND_2_ADDR EQU $2153
    DEF BANK00_HANDLE_FLY_OR_DUNGEON_WARP_ADDR EQU $237C
    DEF BANK00_OVERWORLD_NEW_BATTLE_ADDR EQU $2043
    DEF BANK00_OVERWORLD_DISPLAY_DIALOGUE_ADDR EQU $1E9A
    DEF BANK00_CHECK_IF_DOWN_BUTTON_ADDR EQU $1F02
    DEF BANK00_IS_PLAYER_CONTROLLED_ADDR EQU $3145
    DEF BANK00_CHECK_HIDDEN_EVENT_ADDR EQU $3EE5
    DEF BANK00_IS_SPRITE_OR_SIGN_FRONT_ADDR EQU $253A
    DEF BANK00_NEW_BATTLE_ADDR EQU $209A
    DEF BANK00_BATTLE_OCCURRED_ADDR EQU $204E
    DEF BANK00_COLLISION_CHECK_LAND_ADDR EQU $25E8
    DEF BANK00_EXTRA_WARP_CHECK_ADDR EQU $2300
    DEF BANK00_CHECK_WARPS_COLLISION_ADDR EQU $211D
    DEF BANK00_COLLISION_CHECK_WATER_ADDR EQU $29C8
    DEF BANK00_OVERWORLD_MOVE_AHEAD2_ADDR EQU $1FDF
    DEF BANK00_DO_BIKE_SPEEDUP_ADDR EQU $20B7
    DEF BANK00_ADVANCE_PLAYER_SPRITE_ADDR EQU $2738
    DEF BANK00_CHECK_MAP_CONNECTIONS_ADDR EQU $21D1
    DEF BANK00_CHECK_WARPS_NO_COLLISION_ADDR EQU $20CB
    DEF BANK00_HANDLE_BLACK_OUT_ADDR EQU $2348
    DEF BANK00_RUN_MAP_SCRIPT_ADDR EQU $2A2C
    DEF BANK0F_ANY_PARTY_ALIVE_ADDR EQU $4BA3
    DEF BANK0F_INIT_BATTLE_ADDR EQU $7204
ELIF DEF(_REVA)
    DEF BANK00_LOAD_MAP_DATA_ADDR EQU $2C40
    DEF BANK00_RESET_STRENGTH_BIT_ADDR EQU $2CE6
    DEF BANK00_MAP_ENTRY_AFTER_BATTLE_ADDR EQU $2324
    DEF BANK00_JOYPAD_OVERWORLD_ADDR EQU $294C
    DEF BANK00_OVERWORLD_MOVE_AHEAD_ADDR EQU $1FBA
    DEF BANK00_WARP_FOUND_2_ADDR EQU $2141
    DEF BANK00_HANDLE_FLY_OR_DUNGEON_WARP_ADDR EQU $236A
    DEF BANK00_OVERWORLD_NEW_BATTLE_ADDR EQU $2031
    DEF BANK00_OVERWORLD_DISPLAY_DIALOGUE_ADDR EQU $1E88
    DEF BANK00_CHECK_IF_DOWN_BUTTON_ADDR EQU $1EF0
    DEF BANK00_IS_PLAYER_CONTROLLED_ADDR EQU $3133
    DEF BANK00_CHECK_HIDDEN_EVENT_ADDR EQU $3ED3
    DEF BANK00_IS_SPRITE_OR_SIGN_FRONT_ADDR EQU $2528
    DEF BANK00_NEW_BATTLE_ADDR EQU $2088
    DEF BANK00_BATTLE_OCCURRED_ADDR EQU $203C
    DEF BANK00_COLLISION_CHECK_LAND_ADDR EQU $25D6
    DEF BANK00_EXTRA_WARP_CHECK_ADDR EQU $22EE
    DEF BANK00_CHECK_WARPS_COLLISION_ADDR EQU $210B
    DEF BANK00_COLLISION_CHECK_WATER_ADDR EQU $29B6
    DEF BANK00_OVERWORLD_MOVE_AHEAD2_ADDR EQU $1FCD
    DEF BANK00_DO_BIKE_SPEEDUP_ADDR EQU $20A5
    DEF BANK00_ADVANCE_PLAYER_SPRITE_ADDR EQU $2726
    DEF BANK00_CHECK_MAP_CONNECTIONS_ADDR EQU $21BF
    DEF BANK00_CHECK_WARPS_NO_COLLISION_ADDR EQU $20B9
    DEF BANK00_HANDLE_BLACK_OUT_ADDR EQU $2336
    DEF BANK00_RUN_MAP_SCRIPT_ADDR EQU $2A1A
    DEF BANK0F_ANY_PARTY_ALIVE_ADDR EQU $4BA4
    DEF BANK0F_INIT_BATTLE_ADDR EQU $7209
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
