; Overworld-entry constants verified from the uploaded Midori ROMs.
; BIT_FLY_WARP and BIT_BATTLE_OVER_OR_BLACKOUT are already shared by
; earlier restored systems, so they are reused rather than redefined here.

DEF BIT_WILD_ENCOUNTER_COOLDOWN EQU 0
DEF BIT_DUNGEON_WARP EQU 4
DEF BIT_NO_NPC_FACE_PLAYER EQU 5
DEF BIT_CUR_MAP_LOADED_1 EQU 5
DEF BIT_CUR_MAP_LOADED_2 EQU 6

; Fixed ROMX targets used by the Bank 00 overworld entry path.
DEF BANK1C_HANDLE_MID_JUMP_ADDR EQU $4DEA
DEF BANK03_CLEAR_VARIABLES_ON_ENTER_MAP_ADDR EQU $497B
DEF BANK1C_ENTER_MAP_ANIM_ADDR EQU $4A61
DEF BANK03_CHECK_FORCE_BIKE_OR_SURF_ADDR EQU $49D1

IF DEF(_REV0)
    DEF BANK00_LOAD_MAP_DATA_ADDR EQU $2C52
    DEF BANK00_RESET_STRENGTH_BIT_ADDR EQU $2CF8
    DEF BANK00_MAP_ENTRY_AFTER_BATTLE_ADDR EQU $2336
ELIF DEF(_REVA)
    DEF BANK00_LOAD_MAP_DATA_ADDR EQU $2C40
    DEF BANK00_RESET_STRENGTH_BIT_ADDR EQU $2CE6
    DEF BANK00_MAP_ENTRY_AFTER_BATTLE_ADDR EQU $2324
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
