; Player graphics and bicycle-use constants verified from Bank 00.

DEF ROUTE_23 EQU $22
DEF INDIGO_PLATEAU EQU $09

DEF TILESET_FOREST EQU $03
DEF TILESET_UNDERGROUND EQU $0B
DEF TILESET_CAVERN EQU $11

DEF VRAM_TILESET_BASE EQU $9000
DEF MAP_TILESET_GFX_SIZE EQU $0600

DEF PLAYER_SPRITE_GFX_BANK EQU $05
DEF WALKING_PLAYER_SPRITE_GFX_ADDR EQU $4180
DEF SURFING_PLAYER_SPRITE_GFX_ADDR EQU $76C0
DEF BIKE_PLAYER_SPRITE_GFX_ADDR EQU $4000
DEF VRAM_NPC_SPRITES EQU $8000
DEF PLAYER_SPRITE_GFX_TILE_COUNT EQU $0C
DEF PLAYER_SPRITE_GFX_HALF_OFFSET EQU $C0

IF DEF(_REV0)
    DEF BANK00_LOAD_WALKING_PLAYER_GFX_ADDR EQU $2A5E
    DEF BANK00_LOAD_SURFING_PLAYER_GFX_ADDR EQU $2A66
    DEF BANK00_LOAD_BIKE_PLAYER_GFX_ADDR EQU $2A6E
ELIF DEF(_REVA)
    DEF BANK00_LOAD_WALKING_PLAYER_GFX_ADDR EQU $2A4C
    DEF BANK00_LOAD_SURFING_PLAYER_GFX_ADDR EQU $2A54
    DEF BANK00_LOAD_BIKE_PLAYER_GFX_ADDR EQU $2A5C
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
