; Home pokemon.asm symbols verified against the uploaded Midori ROMs.

DEF wHPBarType EQU $CF7B
DEF wCurPartySpecies EQU $CF78
DEF wWhichPokemon EQU $CF79
DEF wMoves EQU $D0B9
DEF wPokedexNum EQU $D0E3
DEF wTempByteValue EQU $D0E3
DEF wLoadedMonLevel EQU $CFA0
DEF wFrequencyModifier EQU $C0F1
DEF wTempoModifier EQU $C0F2
DEF wMonDataLocation EQU $CC49
DEF wMenuWatchMovingOutOfBounds EQU $CC37
DEF wTopMenuItemY EQU $CC24
DEF wPartyAndBillsPCSavedMenuItem EQU $CC2B
DEF wMenuItemToSwap EQU $CC35
DEF wMenuWrappingEnabled EQU $CC4A
DEF wPartyCount EQU $D123
DEF wPartySpecies EQU $D124
DEF wForcePlayerToChooseMon EQU $D0E4
DEF wPartyMenuAnimMonEnabled EQU $D078
DEF wPartyMenuTypeOrMessageID EQU $D05A
DEF wBattleMonSpecies2 EQU $CFC0
DEF wCurSpecies EQU $D092
DEF wMonHeader EQU $D095
DEF wMonHIndex EQU $D095
DEF wMonHSpriteDim EQU $D09F

DEF hStartTileID EQU $FFE1

DEF PARTY_MON_DATA_BANK EQU $01
DEF PREDEF_INDEX_TO_POKEDEX EQU $3A
DEF NUM_POKEMON EQU 151
DEF RHYDON_INTERNAL_ID EQU $01
DEF vFrontPic EQU $9000
DEF COPY_UNCOMPRESSED_PIC_BANK EQU $0F
DEF CRY_DATA_BANK EQU $0E
DEF CRY_DATA_ADDR EQU $541E
DEF CRY_SFX_START EQU $14
DEF BIT_NO_TEXT_DELAY EQU 6
DEF LV_TILE EQU $6E
DEF LEFT_ALIGN EQU $40

DEF BASE_STATS_BANK EQU $0E
DEF BASE_STATS_ADDR EQU $4000
DEF BASE_DATA_SIZE EQU $1C
DEF FOSSIL_KABUTOPS_INTERNAL_ID EQU $B6
DEF FOSSIL_AERODACTYL_INTERNAL_ID EQU $B7
DEF MON_GHOST_INTERNAL_ID EQU $B8
DEF MEW_INTERNAL_ID EQU $15
DEF FOSSIL_KABUTOPS_PIC_ADDR EQU $64C7
DEF FOSSIL_AERODACTYL_PIC_ADDR EQU $6624
DEF GHOST_PIC_ADDR EQU $67AD
DEF MEW_BASE_STATS_BANK EQU $01
DEF MEW_BASE_STATS_ADDR EQU $4200

DEF BANK04_ERASE_PARTY_MENU_CURSORS_ADDR EQU $5DD1
DEF BANK04_SWITCH_PARTY_MON_ADDR EQU $6116
DEF BANK04_DRAW_PARTY_MENU_ADDR EQU $7A0C
DEF BANK04_REDRAW_PARTY_MENU_ADDR EQU $7A1D
DEF BANK1E_PRINT_STATUS_AILMENT_ADDR EQU $4000
DEF BANK1E_PRINT_STATUS_AILMENT_BANK EQU $1E

IF DEF(_REV0)
    DEF BANK01_LOAD_MON_DATA_ADDR EQU $75C2
    DEF BANK00_LOAD_MON_FRONT_SPRITE_ADDR EQU $3034
    DEF BANK0F_COPY_UNCOMPRESSED_PIC_ADDR EQU $73C5
    DEF BANK00_BANKSWITCH_HOME_ADDR EQU $3606
    DEF BANK00_BANKSWITCH_BACK_ADDR EQU $3617
    DEF BANK00_GB_PAL_WHITE_OUT_DELAY3_ADDR EQU $3E04
    DEF BANK00_LOAD_HP_BAR_STATUS_TILES_ADDR EQU $370A
    DEF BANK00_DRAW_PARTY_MENU_ADDR EQU $2ECB
    DEF BANK00_REDRAW_PARTY_MENU_ADDR EQU $2ED0
    DEF BANK00_HANDLE_PARTY_MENU_INPUT_ADDR EQU $2E51
    DEF BANK00_HANDLE_MENU_INPUT_ADDR EQU $3B0C
    DEF BANK00_PLACE_UNFILLED_ARROW_CURSOR_ADDR EQU $3C1C
    DEF BANK00_ADD_N_TIMES_ADDR EQU $3AD1
ELIF DEF(_REVA)
    DEF BANK01_LOAD_MON_DATA_ADDR EQU $7562
    DEF BANK00_LOAD_MON_FRONT_SPRITE_ADDR EQU $3022
    DEF BANK0F_COPY_UNCOMPRESSED_PIC_ADDR EQU $73CA
    DEF BANK00_BANKSWITCH_HOME_ADDR EQU $35F4
    DEF BANK00_BANKSWITCH_BACK_ADDR EQU $3605
    DEF BANK00_GB_PAL_WHITE_OUT_DELAY3_ADDR EQU $3DF2
    DEF BANK00_LOAD_HP_BAR_STATUS_TILES_ADDR EQU $36F8
    DEF BANK00_DRAW_PARTY_MENU_ADDR EQU $2EB9
    DEF BANK00_REDRAW_PARTY_MENU_ADDR EQU $2EBE
    DEF BANK00_HANDLE_PARTY_MENU_INPUT_ADDR EQU $2E3F
    DEF BANK00_HANDLE_MENU_INPUT_ADDR EQU $3AFA
    DEF BANK00_PLACE_UNFILLED_ARROW_CURSOR_ADDR EQU $3C0A
    DEF BANK00_ADD_N_TIMES_ADDR EQU $3ABF
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
