; Home pokemon.asm symbols verified against the uploaded Midori ROMs.

DEF wHPBarType EQU $CF7B
DEF wCurPartySpecies EQU $CF78
DEF wMoves EQU $D0B9
DEF wPokedexNum EQU $D0E3

DEF hStartTileID EQU $FFE1

DEF PARTY_MON_DATA_BANK EQU $01
DEF PREDEF_INDEX_TO_POKEDEX EQU $3A
DEF NUM_POKEMON EQU 151
DEF RHYDON_INTERNAL_ID EQU $01
DEF vFrontPic EQU $9000
DEF COPY_UNCOMPRESSED_PIC_BANK EQU $0F

IF DEF(_REV0)
    DEF BANK01_LOAD_MON_DATA_ADDR EQU $75C2
    DEF BANK00_LOAD_MON_FRONT_SPRITE_ADDR EQU $3034
    DEF BANK0F_COPY_UNCOMPRESSED_PIC_ADDR EQU $73C5
ELIF DEF(_REVA)
    DEF BANK01_LOAD_MON_DATA_ADDR EQU $7562
    DEF BANK00_LOAD_MON_FRONT_SPRITE_ADDR EQU $3022
    DEF BANK0F_COPY_UNCOMPRESSED_PIC_ADDR EQU $73CA
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
