; RAM/HRAM addresses verified from restored Bank 00 instructions.

DEF sSpriteBuffer1 EQU $A188
DEF sSpriteBuffer2 EQU $A310
DEF SPRITE_BUFFER_SIZE EQU $188

DEF wChannelSoundIDs EQU $C026
DEF wSpriteStateData1 EQU $C100
DEF wSpritePlayerStateData1PictureID EQU $C100
DEF wSpritePlayerStateData1YPixels EQU $C104
DEF wSpritePlayerStateData1XPixels EQU $C106
DEF wSpriteStateData2 EQU $C200
DEF wSpritePlayerStateData2ImageBaseOffset EQU $C20E
DEF wSprite01StateData2OrigFacingDirection EQU $C219
DEF SPRITE_STATE_DATA_LENGTH EQU $100
DEF wShadowOAM EQU $C300
DEF wShadowOAMSize EQU $A0
DEF wTileMap EQU $C3A0
DEF wCurrentMenuItem EQU $CC26
DEF wLastMenuItem EQU $CC2A
DEF wBattleAndStartSavedMenuItem EQU $CC2D
DEF wTextDest EQU $CC3A
DEF wDoNotWaitForButtonPressAfterDisplayingText EQU $CC3C
DEF wLinkMenuSelectionReceiveBuffer EQU $CC3D
DEF wSerialExchangeNybbleTempReceiveData EQU $CC3D
DEF wSerialSyncAndExchangeNybbleReceiveData EQU $CC3D
DEF wSerialExchangeNybbleReceiveData EQU $CC3E
DEF wLinkMenuSelectionSendBuffer EQU $CC42
DEF wSerialExchangeNybbleSendData EQU $CC42
DEF wUnknownSerialCounter EQU $CC47
DEF wEnteringCableClub EQU $CC47
DEF wNameBuffer EQU $CD68
DEF wBuffer EQU $CEE4
DEF wNewSoundID EQU $C0EE
DEF wAudioROMBank EQU $C0EF
DEF wAudioSavedROMBank EQU $C0F0
DEF wTextPredefFlag EQU $CF0C
DEF wSpriteIndex EQU $CF0E
DEF wItemList EQU $CF62
DEF wListMenuID EQU $CF7B
DEF wFontLoaded EQU $CFAB
DEF wAudioFadeOutControl EQU $CFAE
DEF wAudioFadeOutCounterReloadValue EQU $CFAF
DEF wAudioFadeOutCounter EQU $CFB0
DEF wLastMusicSoundID EQU $CFB1
DEF wUpdateSpritesEnabled EQU $CFB2
DEF wEnemyMonNick EQU $CFC1
DEF wBattleMonNick EQU $CFF0
DEF wUnknownSerialCounter2 EQU $D051
DEF wMovingBGTilesCounter2 EQU $D062
DEF wDisableVBlankWYUpdate EQU $D07D
DEF wSpriteCurPosX EQU $D07E
DEF wSpriteCurPosY EQU $D07F
DEF wSpriteWidth EQU $D080
DEF wSpriteHeight EQU $D081
DEF wSpriteInputCurByte EQU $D082
DEF wSpriteInputBitCounter EQU $D083
DEF wSpriteOutputBitOffset EQU $D084
DEF wSpriteLoadFlags EQU $D085
DEF wSpriteUnpackMode EQU $D086
DEF wSpriteFlipped EQU $D087
DEF wSpriteInputPtr EQU $D088
DEF wSpriteOutputPtr EQU $D08A
DEF wSpriteOutputPtrCached EQU $D08C
DEF wSpriteDecodeTable0Ptr EQU $D08E
DEF wSpriteDecodeTable1Ptr EQU $D090
DEF wVBlankSavedROMBank EQU $D0E7
DEF wWalkBikeSurfStateCopy EQU $D0DF
DEF wItemListPointer EQU $D0ED
DEF wLinkState EQU $D0F0
DEF wPlayerName EQU $D11D
DEF wRivalName EQU $D2CE
DEF wLetterPrintingDelayFlags EQU $D2D7
DEF wMapMusicSoundID EQU $D2DA
DEF wMapMusicROMBank EQU $D2DB
DEF wMapPalOffset EQU $D2DC
DEF wCurMap EQU $D2DD
DEF wCurMapTextPtr EQU $D2EB
DEF wNumSprites EQU $D460
DEF wMapSpriteData EQU $D463
DEF wWalkBikeSurfState EQU $D67F
DEF wStatusFlags2 EQU $D6AB
DEF wStatusFlags4 EQU $D6AD
DEF wStatusFlags6 EQU $D6B1
DEF wEventFlagsGotPokedexByte EQU $D6CA
DEF wStack EQU $DFFF

DEF hDMARoutine EQU $FF80
DEF hSoftReset EQU $FF8A
DEF hROMBankTemp EQU $FF8B
DEF hItemPrice EQU $FF8B
DEF hTextID EQU $FF8C
DEF hSpriteIndex EQU $FF8C
DEF hSerialReceivedNewData EQU $FFA9
DEF hSerialConnectionStatus EQU $FFAA
DEF hSerialIgnoringInitialData EQU $FFAB
DEF hSerialSendData EQU $FFAC
DEF hSerialReceiveData EQU $FFAD
DEF hSCX EQU $FFAE
DEF hSCY EQU $FFAF
DEF hWY EQU $FFB0
DEF hJoyPressed EQU $FFB3
DEF hJoyHeld EQU $FFB4
DEF hJoy5 EQU $FFB5
DEF hLoadedROMBank EQU $FFB8
DEF hSavedROMBank EQU $FFB9
DEF hAutoBGTransferEnabled EQU $FFBA
DEF hAutoBGTransferPortion EQU $FFBB
DEF hAutoBGTransferDest EQU $FFBC
DEF hSPTemp EQU $FFBF

DEF hVBlankCopyBGSource EQU $FFC1
DEF hVBlankCopyBGDest EQU $FFC3
DEF hVBlankCopyBGNumRows EQU $FFC5
DEF hVBlankCopySize EQU $FFC6
DEF hVBlankCopySource EQU $FFC7
DEF hVBlankCopyDest EQU $FFC9
DEF hVBlankCopyDoubleSize EQU $FFCB
DEF hVBlankCopyDoubleSource EQU $FFCC
DEF hVBlankCopyDoubleDest EQU $FFCE

DEF hRedrawRowOrColumnMode EQU $FFD0
DEF hRedrawRowOrColumnDest EQU $FFD1
DEF hFrameCounter EQU $FFD5
DEF hVBlankOccurred EQU $FFD6
DEF hTileAnimations EQU $FFD7
DEF hMovingBGTilesCounter1 EQU $FFD8
DEF hWhoseTurn EQU $FFF3

DEF SHADOW_OAM_ENTRY_SIZE EQU 4
DEF SHADOW_OAM_COUNT EQU 40
DEF HIDDEN_SPRITE_Y EQU $A0
