; Start Menu constants and verified targets used by the restored Bank 00 dispatcher.

DEF SFX_START_MENU EQU $8F
DEF EVENT_GOT_POKEDEX_BIT EQU 5

DEF BANK03_PRINT_SAFARI_ZONE_STEPS_ADDR EQU $4B75
DEF BANK04_START_MENU_POKEDEX_ADDR EQU $5AF8
DEF BANK04_START_MENU_POKEMON_ADDR EQU $5B0C
DEF BANK04_START_MENU_ITEM_ADDR EQU $5DE6
DEF BANK04_START_MENU_TRAINER_INFO_ADDR EQU $5F60
DEF BANK04_START_MENU_SAVE_RESET_ADDR EQU $60E6
DEF BANK04_START_MENU_OPTION_ADDR EQU $60F9

IF DEF(_REV0)
    DEF BANK01_DRAW_START_MENU_ADDR EQU $72C1
    DEF BANK00_HANDLE_MENU_INPUT_ADDR EQU $3B08
    DEF BANK00_ERASE_MENU_CURSOR_ADDR EQU $3C29
    DEF BANK00_PLACE_UNFILLED_ARROW_MENU_CURSOR_ADDR EQU $3C1C
    DEF BANK00_SAVE_SCREEN_TILES_2_ADDR EQU $373E
    DEF BANK00_LOAD_TEXT_BOX_TILE_PATTERNS_ADDR EQU $36EA
ELIF DEF(_REVA)
    DEF BANK01_DRAW_START_MENU_ADDR EQU $7266
    DEF BANK00_HANDLE_MENU_INPUT_ADDR EQU $3AF6
    DEF BANK00_ERASE_MENU_CURSOR_ADDR EQU $3C17
    DEF BANK00_PLACE_UNFILLED_ARROW_MENU_CURSOR_ADDR EQU $3C0A
    DEF BANK00_SAVE_SCREEN_TILES_2_ADDR EQU $372C
    DEF BANK00_LOAD_TEXT_BOX_TILE_PATTERNS_ADDR EQU $36D8
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
