; Japanese UI text-box tile IDs verified from Bank 00.

DEF TEXTBOX_TOP_LEFT EQU $79
DEF TEXTBOX_HORIZONTAL EQU $7A
DEF TEXTBOX_TOP_RIGHT EQU $7B
DEF TEXTBOX_VERTICAL EQU $7C
DEF TEXTBOX_BOTTOM_LEFT EQU $7D
DEF TEXTBOX_BOTTOM_RIGHT EQU $7E
DEF TEXT_BLANK EQU $7F
DEF TEXT_DOWN_ARROW EQU $EE
