; Special text-script IDs and synthetic text IDs used by Bank 00.

DEF TX_SCRIPT_POKECENTER_NURSE EQU $FF
DEF TX_SCRIPT_MART EQU $FE
DEF TX_SCRIPT_BILLS_PC EQU $FD
DEF TX_SCRIPT_PLAYERS_PC EQU $FC
DEF TX_SCRIPT_POKECENTER_PC EQU $F9
DEF TX_SCRIPT_PRIZE_VENDOR EQU $F7
DEF TX_SCRIPT_CABLE_CLUB_RECEPTIONIST EQU $F6
DEF TX_SCRIPT_VENDING_MACHINE EQU $F5

; Special hTextID values dispatched directly by DisplayTextID.
DEF TEXT_START_MENU EQU $00
DEF TEXT_MON_FAINTED EQU $D0
DEF TEXT_BLACKED_OUT EQU $D1
DEF TEXT_REPEL_WORE_OFF EQU $D2
DEF TEXT_SAFARI_GAME_OVER EQU $D3

DEF BIT_TEXT_PREDEF EQU 0
DEF BIT_FONT_LOADED EQU 0
DEF BIT_FLY_WARP EQU 3

DEF PRICEDITEMLISTMENU EQU $02
DEF NUM_SPRITESTATEDATA_STRUCTS EQU 16
DEF SPRITESTATEDATA1_LENGTH EQU $10
