; Japanese Generation I text/control byte values verified from Bank 00.

; Text command stream opcodes used by restored data.
DEF TEXT_COMMAND_START EQU $00
DEF TEXT_COMMAND_DECIMAL EQU $09
DEF TEXT_DECIMAL_1BYTE_2DIGITS EQU $12

DEF TEXT_TERMINATOR EQU $50
DEF TEXT_NEXT EQU $4E
DEF TEXT_LINE EQU $4F

DEF TEXT_NULL EQU $00
DEF TEXT_SCROLL EQU $4C
DEF TEXT_CONTINUE_INTERNAL EQU $4B
DEF TEXT_PARAGRAPH EQU $51
DEF TEXT_PLAYER EQU $52
DEF TEXT_RIVAL EQU $53
DEF TEXT_POKE EQU $54
DEF TEXT_CONTINUE EQU $55
DEF TEXT_SIX_DOTS EQU $56
DEF TEXT_DONE EQU $57
DEF TEXT_PROMPT EQU $58
DEF TEXT_TARGET EQU $59
DEF TEXT_USER EQU $5A
DEF TEXT_PC EQU $5B
DEF TEXT_TM EQU $5C
DEF TEXT_TRAINER EQU $5D
DEF TEXT_ROCKET EQU $5E

DEF TEXT_HANDAKUTEN EQU $E4
DEF TEXT_DAKUTEN EQU $E5
DEF FIRST_REGULAR_TEXT_CHAR EQU $60
DEF FIRST_KATAKANA_HANDAKUTEN_CHAR EQU $40
DEF FIRST_HIRAGANA_DAKUTEN_CHAR EQU $20
DEF FIRST_HIRAGANA_HANDAKUTEN_CHAR EQU $44
