; Special text-script IDs used by Bank 00 data.

DEF TX_SCRIPT_POKECENTER_NURSE EQU $FF
DEF TX_SCRIPT_MART EQU $FE
DEF TX_SCRIPT_BILLS_PC EQU $FD
DEF TX_SCRIPT_PLAYERS_PC EQU $FC
DEF TX_SCRIPT_POKECENTER_PC EQU $F9
DEF TX_SCRIPT_PRIZE_VENDOR EQU $F7
