; Text command stream opcodes used by the Bank 00 text command VM.

DEF TX_START EQU $00
DEF TX_RAM EQU $01
DEF TX_BCD EQU $02
DEF TX_MOVE EQU $03
DEF TX_BOX EQU $04
DEF TX_LOW EQU $05
DEF TX_PROMPT_BUTTON EQU $06
DEF TX_SCROLL EQU $07
DEF TX_START_ASM EQU $08
DEF TX_NUM EQU $09
DEF TX_PAUSE EQU $0A
DEF TX_SOUND_GET_ITEM_1 EQU $0B
DEF TX_DOTS EQU $0C
DEF TX_WAIT_BUTTON EQU $0D
DEF TX_SOUND_POKEDEX_RATING EQU $0E
DEF TX_SOUND_GET_ITEM_1_DUPLICATE EQU $0F
DEF TX_SOUND_GET_ITEM_2 EQU $10
DEF TX_SOUND_GET_KEY_ITEM EQU $11
DEF TX_SOUND_CAUGHT_MON EQU $12
DEF TX_SOUND_DEX_PAGE_ADDED EQU $13
DEF TX_SOUND_CRY_NIDORINA EQU $14
DEF TX_SOUND_CRY_PIDGEOT EQU $15
DEF TX_SOUND_CRY_DEWGONG EQU $16
DEF TX_END EQU $50

DEF BIT_TEXT_DELAY EQU 1
DEF BIT_LEFT_ALIGN EQU 6
