; Bank 00 reset vectors, hardware interrupt vectors, revision-specific
; pre-header bytes, and cartridge entry point.

SECTION "RST 00", ROM0[$0000]
    rst $38
    ds $0008 - @, 0

SECTION "RST 08", ROM0[$0008]
    rst $38
    ds $0010 - @, 0

SECTION "RST 10", ROM0[$0010]
    rst $38
    ds $0018 - @, 0

SECTION "RST 18", ROM0[$0018]
    rst $38
    ds $0020 - @, 0

SECTION "RST 20", ROM0[$0020]
    rst $38
    ds $0028 - @, 0

SECTION "RST 28", ROM0[$0028]
    rst $38
    ds $0030 - @, 0

SECTION "RST 30", ROM0[$0030]
    rst $38
    ds $0038 - @, 0

SECTION "RST 38", ROM0[$0038]
    jp $F080
    ds $0040 - @, 0

SECTION "VBlank Vector", ROM0[$0040]
    jp BANK00_VBLANK_ADDR
    ds $0048 - @, 0

SECTION "LCD Vector", ROM0[$0048]
    rst $38
    ds $0050 - @, 0

SECTION "Timer Vector", ROM0[$0050]
    jp BANK00_TIMER_ADDR
    ds $0058 - @, 0

SECTION "Serial Vector", ROM0[$0058]
    jp BANK00_SERIAL_ADDR
    ds $0060 - @, 0

SECTION "Joypad Vector", ROM0[$0060]
    reti
    ds $0068 - @, 0

SECTION "Revision Garbage Header", ROM0[$0068]
IF DEF(_REV0)
    INCBIN "garbage/rev0/header.bin"
ELIF DEF(_REVA)
    INCBIN "garbage/reva/header.bin"
ELSE
    FAIL "Define exactly one Midori revision: _REV0 or _REVA"
ENDC
ASSERT @ == $0100

SECTION "Cartridge Header", ROM0[$0100]
Start::
    nop
    jp _Start

    ; $0104-$014F is generated by rgbfix during the full-ROM build.
    ds $0150 - @, 0
