; Generated by tools/disassemble_gb_cfg.py; do not edit by hand.

SECTION "Bootstrap CFG 09da", ROM0[$09da]

Block_09da::
    di
    xor a
    ldh [$ff00 + $0f], a
    ldh [$ff00 + $ff], a
    ldh [$ff00 + $43], a
    ldh [$ff00 + $42], a
    ldh [$ff00 + $01], a
    ldh [$ff00 + $02], a
    ldh [$ff00 + $4b], a
    ldh [$ff00 + $4a], a
    ldh [$ff00 + $06], a
    ldh [$ff00 + $07], a
    ldh [$ff00 + $47], a
    ldh [$ff00 + $48], a
    ldh [$ff00 + $49], a
    ld a, $80
    ldh [$ff00 + $40], a
    call $0167
    ld sp, $dfff
    ld hl, $c000
    ld bc, $2000
    ld [hl], $00
    inc hl
    dec bc
    ld a, b
    or c
    jr nz $0a06

SECTION "Bootstrap CFG 0a0e", ROM0[$0a0e]

Block_0a0e::
    call $0a8c
    ld hl, $ff80
    ld bc, $007f
    call $372a
    call $0188
    ld a, $01
    ldh [$ff00 + $b8], a
    ld [$2000], a
    call $4750
    xor a
    ldh [$ff00 + $d7], a
    ldh [$ff00 + $41], a
    ldh [$ff00 + $ae], a
    ldh [$ff00 + $af], a
    ldh [$ff00 + $0f], a
    ld a, $0d
    ldh [$ff00 + $ff], a
    ld a, $90
    ldh [$ff00 + $b0], a
    ldh [$ff00 + $4a], a
    ld a, $07
    ldh [$ff00 + $4b], a
    ld a, $ff
    ldh [$ff00 + $aa], a
    ld h, $98
    call $0787
    ld h, $9c
    call $0787
    ld a, $e3
    ldh [$ff00 + $40], a
    ld a, $10
    ldh [$ff00 + $8a], a
    call $0a96
    ei
    ld a, $40
    call $3e9d
    ld a, $1f
    ld [$c0ef], a
    ld [$c0f0], a
    ld a, $9c
    ld [$ffbd], a
    xor a
    ld [$ffbc], a
    dec a
    ld [$cfb2], a
    ld a, $32
    call $3e9d
    call $0167
    call $0a8c
    call $3e0c
    call $0188
    ld a, $e3
    ldh [$ff00 + $40], a
    jp $476e
