; Generated by tools/disassemble_gb_basic_block.py; do not edit by hand.
SECTION "Bootstrap Block", ROM0[$09da]

BootstrapBlock::
    di
    xor a
    ldh [$ff00 + $0f], a
    ldh [$ff00 + $ff], a
    ldh [$ff00 + $43], a
    ldh [$ff00 + $42], a
    ldh [$ff00 + $01], a
    ldh [$ff00 + $02], a
    ldh [$ff00 + $4b], a
    ldh [$ff00 + $4a], a
    ldh [$ff00 + $06], a
    ldh [$ff00 + $07], a
    ldh [$ff00 + $47], a
    ldh [$ff00 + $48], a
    ldh [$ff00 + $49], a
    ld a, $80
    ldh [$ff00 + $40], a
    call $0167
    ld sp, $dfff
    ld hl, $c000
    ld bc, $2000
    ld [hl], $00
    inc hl
    dec bc
    ld a, b
    or c
    jr nz $0a06
